"""create quran ayat and embeddings

Revision ID: 75a4d3050f83
Revises: 675461225969
Create Date: 2026-05-15 15:12:13.149353

"""

from typing import Sequence, Union
from pgvector.sqlalchemy import Vector  # type: ignore[import-untyped]

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75a4d3050f83"
down_revision: Union[str, Sequence[str], None] = "675461225969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quran_ayat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("surah_number", sa.Integer(), nullable=False),
        sa.Column("ayah_number", sa.Integer(), nullable=False),
        sa.Column("translation_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ayah_number > 0", name="ck_quran_ayat_number_positive"),
        sa.CheckConstraint(
            "length(trim(translation_text)) > 0",
            name="ck_quran_ayat_translation_text_not_empty",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "surah_number", "ayah_number", name="uq_quran_ayat_surah_ayah"
        ),
    )
    op.create_table(
        "ayah_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quran_ayah_id", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=False),
        sa.Column("embedding_provider", sa.String(length=100), nullable=False),
        sa.Column("embedding_model", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quran_ayah_id"], ["quran_ayat.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quran_ayah_id", name="uq_ayah_embeddings_quran_ayah_id"),
    )
    op.execute(
        "CREATE INDEX ix_ayah_embeddings_embedding_hnsw "
        "ON ayah_embeddings USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ayah_embeddings_embedding_hnsw", table_name="ayah_embeddings")
    op.drop_table("ayah_embeddings")
    op.drop_table("quran_ayat")
    # ### end Alembic commands ###
